export const CARRO_IMGS = {
  frontal: '/frente.png',
  traseira: '/traseira.png',
  esquerda: '/lateral esquerda.png',
  direita: '/lateral direita.png'
};

export const MOTO_IMGS = {
  moto_frontal: '/img/extracted_8.png',
  moto_traseira: '/img/extracted_9.png',
  moto_direita: '/img/extracted_10.png',
  moto_esquerda: '/img/extracted_11.png'
};

export const DAN_DIAGRAMAS = {
  carro: {
    frontal: { img: 'frontal', vb: "0 0 900 500", pontos: [
      { id: 'F1', label: 'Capô', px: 40.2, py: 41.4 },
      { id: 'F2', label: 'Para-choque', px: 49.6, py: 51.2 },
      { id: 'F3', label: 'Para-Brisa', px: 54.9, py: 24.8 },
      { id: 'F4', label: 'Farol Direito', px: 28.7, py: 54.4 },
      { id: 'F5', label: 'Farol Esquerdo', px: 72.6, py: 53.4 },
      { id: 'F6', label: 'Farol de Milha Direito', px: 29.9, py: 75.6 },
      { id: 'F7', label: 'Farol de Milha Esquerdo', px: 74.3, py: 75.4 },
      { id: 'F8', label: 'Grade Superior Frontal', px: 61.9, py: 59.8 },
      { id: 'F9', label: 'Grade Inferior Frontal', px: 60.9, py: 79.6 },
      { id: 'F10', label: 'Retrovisor Direito', px: 22.9, py: 34.0 },
      { id: 'F11', label: 'Retrovisor Esquerdo', px: 77.3, py: 34.0 },
      { id: 'F12', label: 'Para-lama Dianteiro Esquerdo', px: 20.4, py: 65.8 },
      { id: 'F13', label: 'Para-lama Dianteiro Direito', px: 79.1, py: 61.8 },
      { id: 'F14', label: 'Placa Dianteira', px: 49.3, py: 75.6 },
    ] },
    traseira: { img: 'traseira', vb: "0 0 880 490", pontos: [
      { id: 'T1', label: 'Lanterna Traseira Esquerda', px: 29.1, py: 55.7 },
      { id: 'T2', label: 'Lanterna Traseira Direita', px: 70.8, py: 55.5 },
      { id: 'T3', label: 'Vidro Traseiro / Vigia', px: 42.6, py: 39.0 },
      { id: 'T4', label: 'Tampa Porta-Malas', px: 41.0, py: 66.7 },
      { id: 'T5', label: 'Para-choque Traseiro', px: 55.8, py: 73.3 },
      { id: 'T6', label: 'Escapamento', px: 35.7, py: 90.4 },
      { id: 'T7', label: 'Refletor Esquerdo', px: 31.5, py: 81.0 },
      { id: 'T8', label: 'Refletor Direito', px: 68.8, py: 82.9 },
      { id: 'T9', label: 'Emblema', px: 50.0, py: 48.2 },
      { id: 'T10', label: 'Placa Traseira', px: 50.1, py: 58.4 },
    ] },
    esquerda: { img: 'esquerda', vb: "0 0 880 490", pontos: [
      { id: 'E1', label: 'Roda Dianteira Esquerda', px: 21.9, py: 81.0 },
      { id: 'E2', label: 'Roda Traseira Esquerda', px: 78.1, py: 80.2 },
      { id: 'E3', label: 'Porta Dianteira Esquerda', px: 43.4, py: 68.0 },
      { id: 'E4', label: 'Porta Traseira Esquerda', px: 62.4, py: 68.2 },
      { id: 'E5', label: 'Vidro Dianteiro Esquerdo', px: 46.6, py: 46.3 },
      { id: 'E6', label: 'Vidro Traseiro Esquerdo', px: 62.7, py: 43.7 },
      { id: 'E7', label: 'Para-lama Dianteiro Esquerdo', px: 12.8, py: 78.0 },
    ] },
    direita: { img: 'direita', vb: "0 0 880 490", pontos: [
      { id: 'D1', label: 'Roda Dianteira Direita', px: 19.9, py: 73.9 },
      { id: 'D2', label: 'Roda Traseira Direita', px: 73.8, py: 74.3 },
      { id: 'D3', label: 'Porta Dianteira Direita', px: 55.1, py: 63.9 },
      { id: 'D4', label: 'Porta Traseira Direita', px: 35.2, py: 67.1 },
      { id: 'D5', label: 'Vidro Dianteiro Direito', px: 49.1, py: 43.7 },
      { id: 'D6', label: 'Vidro Traseiro Direito', px: 33.6, py: 40.6 },
      { id: 'D7', label: 'Para-lama Dianteiro Direito', px: 83.4, py: 69.4 },
    ] },
  },
  moto: {
    frontal: { img: 'moto_frontal', vb: "0 0 400 500", pontos: [
      { id: 'F1', label: 'Farol frontal', px: 50, py: 18 },
      { id: 'F2', label: 'Carenagem frontal esq.', px: 32, py: 33 },
      { id: 'F3', label: 'Carenagem frontal dir.', px: 68, py: 33 },
      { id: 'F4', label: 'Guidão esquerdo', px: 18, py: 22 },
      { id: 'F5', label: 'Guidão direito', px: 82, py: 22 },
      { id: 'F6', label: 'Painel / Instrumentos', px: 50, py: 26 },
      { id: 'F7', label: 'Paralama dianteiro', px: 50, py: 52 },
      { id: 'F8', label: 'Bengala esquerda', px: 40, py: 55 },
      { id: 'F9', label: 'Bengala direita', px: 60, py: 55 },
      { id: 'F10', label: 'Pneu dianteiro', px: 50, py: 80 },
    ] },
    traseira: { img: 'moto_traseira', vb: "0 0 400 500", pontos: [
      { id: 'T1', label: 'Lanterna traseira', px: 50, py: 17 },
      { id: 'T2', label: 'Baú / Bagageiro', px: 50, py: 27 },
      { id: 'T3', label: 'Assento', px: 50, py: 37 },
      { id: 'T4', label: 'Carenagem traseira esq.', px: 30, py: 45 },
      { id: 'T5', label: 'Carenagem traseira dir.', px: 70, py: 45 },
      { id: 'T6', label: 'Paralama traseiro', px: 50, py: 57 },
      { id: 'T7', label: 'Placa', px: 50, py: 68 },
      { id: 'T8', label: 'Pneu traseiro', px: 50, py: 82 },
    ] },
    esquerda: { img: 'moto_esquerda', vb: "0 0 600 400", pontos: [
      { id: 'E1', label: 'Farol dianteiro', px: 13, py: 30 },
      { id: 'E2', label: 'Guidão esq.', px: 20, py: 18 },
      { id: 'E3', label: 'Painel', px: 22, py: 30 },
      { id: 'E4', label: 'Tanque esq.', px: 35, py: 28 },
      { id: 'E5', label: 'Assento', px: 50, py: 25 },
      { id: 'E6', label: 'Carenagem lateral esq.', px: 35, py: 48 },
      { id: 'E7', label: 'Motor / Cárter esq.', px: 38, py: 62 },
      { id: 'E8', label: 'Escapamento', px: 62, py: 70 },
      { id: 'E9', label: 'Pneu dianteiro', px: 14, py: 78 },
      { id: 'E10', label: 'Pneu traseiro', px: 82, py: 78 },
      { id: 'E11', label: 'Paralama dianteiro', px: 14, py: 52 },
      { id: 'E12', label: 'Paralama traseiro', px: 78, py: 55 },
      { id: 'E13', label: 'Lanterna traseira', px: 88, py: 30 },
    ] },
    direita: { img: 'moto_direita', vb: "0 0 600 400", pontos: [
      { id: 'D1', label: 'Farol dianteiro', px: 87, py: 30 },
      { id: 'D2', label: 'Guidão dir.', px: 80, py: 18 },
      { id: 'D3', label: 'Painel', px: 78, py: 30 },
      { id: 'D4', label: 'Tanque dir.', px: 65, py: 28 },
      { id: 'D5', label: 'Assento', px: 50, py: 25 },
      { id: 'D6', label: 'Carenagem lateral dir.', px: 65, py: 48 },
      { id: 'D7', label: 'Motor / Cárter dir.', px: 62, py: 62 },
      { id: 'D8', label: 'Freio / Pedal dir.', px: 38, py: 70 },
      { id: 'D9', label: 'Pneu dianteiro', px: 86, py: 78 },
      { id: 'D10', label: 'Pneu traseiro', px: 18, py: 78 },
      { id: 'D11', label: 'Paralama dianteiro', px: 86, py: 52 },
      { id: 'D12', label: 'Paralama traseiro', px: 22, py: 55 },
      { id: 'D13', label: 'Lanterna traseira', px: 12, py: 30 },
    ] },
  }
};

export const V360_MOTO_PARTES = [
  { n: "01", t: "Farol", g: "FRONTAL" },
  { n: "02", t: "Paralama dianteiro", g: "FRONTAL" },
  { n: "03", t: "Pneu dianteiro", g: "FRONTAL" },
  { n: "04", t: "Roda dianteira", g: "FRONTAL" },
  { n: "05", t: "Suspensão dianteira — direita", g: "FRONTAL" },
  { n: "06", t: "Suspensão dianteira — esquerda", g: "FRONTAL" },
  { n: "07", t: "Seta dianteira — direita", g: "FRONTAL" },
  { n: "08", t: "Seta dianteira — esquerda", g: "FRONTAL" },
  { n: "09", t: "Retrovisor — direita", g: "LADO DIREITO" },
  { n: "10", t: "Manete — direita", g: "LADO DIREITO" },
  { n: "11", t: "Carenagem lateral — direita", g: "LADO DIREITO" },
  { n: "12", t: "Pedaleira — direita", g: "LADO DIREITO" },
  { n: "13", t: "Escapamento — direita", g: "LADO DIREITO" },
  { n: "14", t: "Pedal de freio — direita", g: "LADO DIREITO" },
  { n: "15", t: "Balança — direita", g: "LADO DIREITO" },
  { n: "16", t: "Retrovisor — esquerda", g: "LADO ESQUERDO" },
  { n: "17", t: "Manete — esquerda", g: "LADO ESQUERDO" },
  { n: "18", t: "Carenagem lateral — esquerda", g: "LADO ESQUERDO" },
  { n: "19", t: "Pedaleira — esquerda", g: "LADO ESQUERDO" },
  { n: "20", t: "Pedal de câmbio — esquerda", g: "LADO ESQUERDO" },
  { n: "21", t: "Relação / corrente — esquerda", g: "LADO ESQUERDO" },
  { n: "22", t: "Descanso lateral — esquerda", g: "LADO ESQUERDO" },
  { n: "23", t: "Balança — esquerda", g: "LADO ESQUERDO" },
  { n: "24", t: "Lanterna traseira", g: "TRASEIRO" },
  { n: "25", t: "Seta traseira — direita", g: "TRASEIRO" },
  { n: "26", t: "Seta traseira — esquerda", g: "TRASEIRO" },
  { n: "27", t: "Pneu traseiro", g: "TRASEIRO" },
  { n: "28", t: "Roda traseira", g: "TRASEIRO" },
  { n: "29", t: "Amortecedor", g: "TRASEIRO" },
  { n: "30", t: "Alça do garupa", g: "TRASEIRO" },
  { n: "31", t: "Placa / suporte", g: "TRASEIRO" },
  { n: "32", t: "Tanque", g: "TRASEIRO" },
  { n: "33", t: "Banco", g: "TRASEIRO" }
];
